import { createContext } from 'react'

export interface AccordionItemContextValue {
  /**
   * Id of the panel this item's button should target via
   * `aria-controls`. Generated by `AccordionItem`'s `useId()` call
   * and applied to the sibling `<div class="usa-accordion__content">`.
   */
  panelId: string
  /** Whether the panel should be expanded in the initial render. */
  expanded: boolean
}

/**
 * Per-item context carrying the panel id that `AccordionHeading`'s
 * button needs to target. Lives in its own module so
 * `AccordionHeading.tsx` can consume it without importing
 * `Accordion.tsx` (which imports `AccordionHeading` itself for the
 * slot-filter identity check — defining the context in either file
 * would create a circular import).
 *
 * Each `<AccordionItem>` wraps its children in its own Provider so
 * sibling items don't share panel ids.
 */
export const AccordionItemContext = createContext<AccordionItemContextValue | null>(null)
